name: 功能建议
description: 为这个项目提供一个很棒的想法
body:
  - type: markdown
    attributes:
      value: 感谢您的参与。
  - type: textarea
    id: description
    attributes:
      label: 一个很棒的想法
    validations:
      required: true
